// == 200 == //
const OK = 200;
const CREATED = 201;
const ACCEPTED = 202;

// == 400 == //
const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const PAYMENT_REQUIRED = 402;
const FORBIDDEN = 403;
const NOT_FOUND = 404;

export {
  OK,
  CREATED,
  ACCEPTED,
  UNAUTHORIZED,
  PAYMENT_REQUIRED,
  FORBIDDEN,
  NOT_FOUND,
  BAD_REQUEST,
};
